#!/usr/bin/env python3
"""Generate portable LaTeX figure fragments from constitutional-review reports."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPORT_DIR = ROOT / "reports"
FIGURE_DIR = ROOT / "paper" / "figures"
BASELINE_CSV = REPORT_DIR / "constitutional-review-campaign-v0.csv"
PAIRED_CSV = REPORT_DIR / "constitutional-review-paired-import-v1.csv"

SCENARIO_LABELS = {
    "current-federal-court": "CUR",
    "eighteen-year-terms": "18Y",
    "fifteen-justice-commission": "15J",
    "supermajority-invalidation": "SUP",
    "strict-recusal-court": "REC",
    "reasoned-emergency-review": "EMR",
    "panel-en-banc-review": "PAN",
    "dual-cross-checking-courts": "DUAL",
    "constitutional-council": "COUNC",
    "legislative-override-court": "OVR",
    "accountability-retention-court": "RET",
    "independence-accountability-hybrid": "HYB",
}

EMERGENCY_SCENARIOS = [
    "current-federal-court",
    "strict-recusal-court",
    "reasoned-emergency-review",
    "dual-cross-checking-courts",
    "constitutional-council",
    "independence-accountability-hybrid",
]

PAIRED_SCENARIOS = [
    ("current-federal-court", "red"),
    ("reasoned-emergency-review", "black"),
    ("dual-cross-checking-courts", "black!55"),
    ("constitutional-council", "black!35"),
    ("independence-accountability-hybrid", "black!75"),
]

PAIRED_LABEL_OFFSETS = {
    "current-federal-court": -1.0,
    "reasoned-emergency-review": -1.0,
    "dual-cross-checking-courts": 3.0,
    "constitutional-council": 1.0,
    "independence-accountability-hybrid": -1.5,
}

PAIRED_CASES = [
    ("synthetic-baseline", "SB"),
    ("legislative-all", "ALL"),
    ("legislative-high-capture", "CAP"),
    ("legislative-high-volatility", "VOL"),
    ("legislative-low-mandate", "MAND"),
]


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def baseline_rows() -> list[dict[str, str]]:
    return [row for row in read_rows(BASELINE_CSV) if row["caseKey"] == "baseline"]


def row_float(row: dict[str, str], field: str) -> float:
    return float(row[field])


def coord(value: float, lower: float, upper: float, start: float, length: float) -> float:
    if upper == lower:
        return start + (length / 2.0)
    return start + ((value - lower) / (upper - lower)) * length


def write(name: str, content: str) -> None:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    (FIGURE_DIR / name).write_text(content, encoding="utf-8")


def fmt(value: float) -> str:
    return f"{value:.1f}"


def generate_model_pipeline() -> None:
    write(
        "model_pipeline.tex",
        r"""% Auto-generated by paper/scripts/generate_figures.py
\begingroup
\setlength{\unitlength}{1mm}
\begin{picture}(128,55)
\scriptsize
\put(2,34){\framebox(28,13){\shortstack[c]{Scenario\\catalog\\rules}}}
\put(34,34){\framebox(28,13){\shortstack[c]{Shared worlds\\and dockets}}}
\put(66,34){\framebox(28,13){\shortstack[c]{Review\\pipeline}}}
\put(98,34){\framebox(28,13){\shortstack[c]{Metrics\\and reports}}}
\put(30,40.5){\vector(1,0){4}}
\put(62,40.5){\vector(1,0){4}}
\put(94,40.5){\vector(1,0){4}}
\put(68,20){\framebox(24,10){\shortstack[c]{intake\\emergency\\merits}}}
\put(68,8){\framebox(24,10){\shortstack[c]{compliance\\reaction\\cost}}}
\put(80,34){\vector(0,-1){4}}
\put(80,20){\vector(0,-1){2}}
\put(34,8){\framebox(28,10){\shortstack[c]{legislative\\CSV outputs}}}
\put(62,13){\vector(1,0){6}}
\put(50,18){\vector(0,1){16}}
\put(20,27){\makebox(0,0){\shortstack[c]{appointment, size, tenure,\\thresholds, councils, overrides}}}
\put(112,27){\makebox(0,0){\shortstack[c]{CSV, Markdown,\\provenance, paper figures}}}
\put(80,3){\makebox(0,0){\shortstack[c]{Dynamic replacement, lower-court routing,\\emergency relief, merits review, enforcement}}}
\end{picture}
\endgroup
""",
    )


def generate_emergency_bars(rows: list[dict[str, str]]) -> None:
    by_key = {row["scenarioKey"]: row for row in rows}
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        r"\begingroup",
        r"\setlength{\unitlength}{1mm}",
        r"\begin{picture}(128,72)",
        r"\scriptsize",
    ]
    left, width = 36.0, 78.0
    y_top, gap = 56.0, 8.0
    for tick in [0.0, 0.25, 0.5, 0.75, 1.0]:
        x = left + (tick * width)
        lines.append(rf"\put({fmt(x)},10){{\color{{black!15}}\line(0,1){{50}}}}")
        label = "1" if tick == 1.0 else ("0" if tick == 0.0 else f"{tick:.2f}".rstrip("0"))
        lines.append(rf"\put({fmt(x)},6){{\makebox(0,0){{{label}}}}}")
    lines.append(rf"\put({fmt(left)},10){{\line(1,0){{{fmt(width)}}}}}")
    lines.append(rf"\put({fmt(left)},10){{\line(0,1){{50}}}}")
    lines.append(r"\put(36,64){\color{black}\rule{6mm}{1.2mm}}")
    lines.append(r"\put(44,64){\makebox(0,0)[l]{shadow-docket abuse}}")
    lines.append(r"\put(76,64){\color{black!55}\rule{6mm}{1.2mm}}")
    lines.append(r"\put(84,64){\makebox(0,0)[l]{reason-giving}}")
    lines.append(r"\put(36,60.5){\color{black!25}\rule{6mm}{1.2mm}}")
    lines.append(r"\put(44,60.5){\makebox(0,0)[l]{merits follow-up}}")
    for i, key in enumerate(EMERGENCY_SCENARIOS):
        row = by_key[key]
        y = y_top - (i * gap)
        label = SCENARIO_LABELS[key]
        label_color = "red" if key == "current-federal-court" else "black"
        lines.append(rf"\put(32,{fmt(y)}){{\makebox(0,0)[r]{{\color{{{label_color}}}{label}}}}}")
        for offset, field, color in [
            (1.8, "shadowDocketAbuse", "black"),
            (0.0, "emergencyReasonGivingRate", "black!55"),
            (-1.8, "meritsFollowUpRate", "black!25"),
        ]:
            bar = row_float(row, field) * width
            lines.append(rf"\put({fmt(left)},{fmt(y + offset)}){{\color{{{color}}}\rule{{{fmt(bar)}mm}}{{1.2mm}}}}")
    lines.append(r"\put(75,2){\makebox(0,0){rate}}")
    lines.extend([r"\end{picture}", r"\endgroup", ""])
    write("emergency_docket_bars.tex", "\n".join(lines))


def generate_cost_score_scatter(rows: list[dict[str, str]]) -> None:
    left, bottom, width, height = 22.0, 15.0, 92.0, 58.0
    x_min, x_max = 0.44, 0.61
    y_min, y_max = 0.54, 0.72
    offsets = {
        "CUR": (2.5, -4.0, "l"),
        "18Y": (2.5, -2.0, "l"),
        "15J": (-2.5, 4.0, "r"),
        "SUP": (-2.5, -3.5, "r"),
        "REC": (2.5, -2.5, "l"),
        "EMR": (-2.5, 5.0, "r"),
        "PAN": (2.5, -3.0, "l"),
        "DUAL": (2.5, 2.0, "l"),
        "COUNC": (2.5, 4.0, "l"),
        "OVR": (2.5, 2.0, "l"),
        "RET": (2.5, 0.0, "l"),
        "HYB": (2.5, 2.0, "l"),
    }
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        r"\begingroup",
        r"\setlength{\unitlength}{1mm}",
        r"\begin{picture}(128,86)",
        r"\scriptsize",
    ]
    for tick in [0.45, 0.50, 0.55, 0.60]:
        x = coord(tick, x_min, x_max, left, width)
        lines.append(rf"\put({fmt(x)},{fmt(bottom)}){{\color{{black!15}}\line(0,1){{{fmt(height)}}}}}")
        lines.append(rf"\put({fmt(x)},{fmt(bottom - 4)}){{\makebox(0,0){{{tick:.2f}}}}}")
    for tick in [0.55, 0.60, 0.65, 0.70]:
        y = coord(tick, y_min, y_max, bottom, height)
        lines.append(rf"\put({fmt(left)},{fmt(y)}){{\color{{black!15}}\line(1,0){{{fmt(width)}}}}}")
        lines.append(rf"\put({fmt(left - 4)},{fmt(y)}){{\makebox(0,0)[r]{{{tick:.2f}}}}}")
    lines.append(rf"\put({fmt(left)},{fmt(bottom)}){{\line(1,0){{{fmt(width)}}}}}")
    lines.append(rf"\put({fmt(left)},{fmt(bottom)}){{\line(0,1){{{fmt(height)}}}}}")
    for row in rows:
        key = row["scenarioKey"]
        label = SCENARIO_LABELS[key]
        x = coord(row_float(row, "totalInstitutionalCost"), x_min, x_max, left, width)
        y = coord(row_float(row, "directionalScore"), y_min, y_max, bottom, height)
        color = "red" if key == "current-federal-court" else "black"
        size = 2.1 if key == "current-federal-court" else 1.7
        lines.append(rf"\put({fmt(x)},{fmt(y)}){{\makebox(0,0){{\color{{{color}}}\rule{{{size}mm}}{{{size}mm}}}}}}")
        dx, dy, align = offsets[label]
        lines.append(rf"\put({fmt(x + dx)},{fmt(y + dy)}){{\makebox(0,0)[{align}]{{\color{{{color}}}{label}}}}}")
    lines.append(r"\put(68,4){\makebox(0,0){total institutional cost}}")
    lines.append(r"\put(4,45){\rotatebox{90}{\makebox(0,0){directional diagnostic score}}}")
    lines.extend([r"\end{picture}", r"\endgroup", ""])
    write("cost_score_scatter.tex", "\n".join(lines))


def generate_paired_lines() -> None:
    rows = read_rows(PAIRED_CSV)
    values = {
        (row["caseKey"], row["scenarioKey"]): row_float(row, "directionalScore")
        for row in rows
    }
    left, bottom, width, height = 24.0, 14.0, 82.0, 58.0
    y_min, y_max = 0.50, 0.84
    x_positions = [
        left + (idx * (width / (len(PAIRED_CASES) - 1)))
        for idx in range(len(PAIRED_CASES))
    ]
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        r"\begingroup",
        r"\setlength{\unitlength}{1mm}",
        r"\begin{picture}(128,88)",
        r"\scriptsize",
    ]
    for tick in [0.50, 0.60, 0.70, 0.80]:
        y = coord(tick, y_min, y_max, bottom, height)
        lines.append(rf"\put({fmt(left)},{fmt(y)}){{\color{{black!15}}\line(1,0){{{fmt(width)}}}}}")
        lines.append(rf"\put({fmt(left - 4)},{fmt(y)}){{\makebox(0,0)[r]{{{tick:.2f}}}}}")
    for x, (_, label) in zip(x_positions, PAIRED_CASES):
        lines.append(rf"\put({fmt(x)},{fmt(bottom)}){{\color{{black!12}}\line(0,1){{{fmt(height)}}}}}")
        lines.append(rf"\put({fmt(x)},{fmt(bottom - 4)}){{\makebox(0,0){{{label}}}}}")
    lines.append(rf"\put({fmt(left)},{fmt(bottom)}){{\line(1,0){{{fmt(width)}}}}}")
    lines.append(rf"\put({fmt(left)},{fmt(bottom)}){{\line(0,1){{{fmt(height)}}}}}")
    for scenario_key, color in PAIRED_SCENARIOS:
        points: list[tuple[float, float]] = []
        for x, (case_key, _) in zip(x_positions, PAIRED_CASES):
            y = coord(values[(case_key, scenario_key)], y_min, y_max, bottom, height)
            points.append((x, y))
        lines.append(r"\linethickness{0.35mm}")
        for (x1, y1), (x2, y2) in zip(points, points[1:]):
            mid_x = (x1 + x2) / 2.0
            mid_y = (y1 + y2) / 2.0
            lines.append(rf"{{\color{{{color}}}\qbezier[22]({fmt(x1)},{fmt(y1)})({fmt(mid_x)},{fmt(mid_y)})({fmt(x2)},{fmt(y2)})}}")
        lines.append(r"\linethickness{0.25mm}")
        for x, y in points:
            lines.append(rf"\put({fmt(x)},{fmt(y)}){{\makebox(0,0){{\color{{{color}}}\rule{{1.5mm}}{{1.5mm}}}}}}")
        end_x, end_y = points[-1]
        label_y = end_y + PAIRED_LABEL_OFFSETS.get(scenario_key, 0.0)
        lines.append(rf"\put({fmt(end_x + 3)},{fmt(label_y)}){{\makebox(0,0)[l]{{\color{{{color}}}{SCENARIO_LABELS[scenario_key]}}}}}")
    lines.append(r"\put(65,4){\makebox(0,0){docket source}}")
    lines.append(r"\put(12,75){\makebox(0,0){score}}")
    lines.append(r"\put(65,80){\makebox(0,0){SB synthetic; ALL all imports; CAP high capture; VOL high volatility; MAND low mandate}}")
    lines.extend([r"\end{picture}", r"\endgroup", ""])
    write("paired_import_lines.tex", "\n".join(lines))


def main() -> None:
    rows = baseline_rows()
    generate_model_pipeline()
    generate_emergency_bars(rows)
    generate_cost_score_scatter(rows)
    generate_paired_lines()


if __name__ == "__main__":
    main()
