#!/usr/bin/env python3
"""Generate compact JLC-facing LaTeX tables from simulator artifacts."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPORT_DIR = ROOT / "reports"
CONFIG_DIR = ROOT / "config" / "calibration"
TABLE_DIR = ROOT / "paper" / "tables"
BASELINE_CSV = REPORT_DIR / "constitutional-review-campaign-v0.csv"
BASELINE_INTERVALS_CSV = REPORT_DIR / "constitutional-review-campaign-v0-intervals.csv"

SCENARIO_LABELS = {
    "current-federal-court": "CUR",
    "eighteen-year-terms": "18Y",
    "fifteen-justice-commission": "15J",
    "supermajority-invalidation": "SUP",
    "strict-recusal-court": "REC",
    "reasoned-emergency-review": "EMR",
    "panel-en-banc-review": "PAN",
    "dual-cross-checking-courts": "DUAL",
    "constitutional-council": "COUNC",
    "legislative-override-court": "OVR",
    "accountability-retention-court": "RET",
    "independence-accountability-hybrid": "HYB",
}

SCENARIO_ORDER = list(SCENARIO_LABELS)

CALIBRATION_ROWS = [
    ("us-supreme-court-2000-2024.csv", "scdb-modern-merits-2000-2024", "doctrine_mix.speech"),
    ("us-supreme-court-2000-2024.csv", "scdb-modern-merits-2000-2024", "doctrine_mix.equality"),
    ("us-supreme-court-2024-public-emergency.csv", "scotus-emergency-2024-2025", "emergency_relief_rate"),
    ("us-supreme-court-2024-public-emergency.csv", "scotus-emergency-2024-2025", "emergency_reason_giving_rate"),
    ("us-supreme-court-2024-public-emergency.csv", "gallup-court-confidence-2024", "public_trust"),
    ("germany-bverfg-2024.csv", "germany-bverfg-2024", "intake_acceptance_rate"),
    ("canada-scc-recent.csv", "canada-scc-recent", "intake_acceptance_rate"),
    ("france-conseil-qpc.csv", "france-conseil-qpc", "merits_invalidation_rate"),
    ("south-africa-constcourt-recent.csv", "south-africa-constcourt-recent", "review_rate"),
]


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def latex_escape(value: str) -> str:
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    return "".join(replacements.get(char, char) for char in value)


def num(value: str | float) -> str:
    return f"{float(value):.3f}"


def write(name: str, content: str) -> None:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    (TABLE_DIR / name).write_text(content, encoding="utf-8")


def generate_baseline_results() -> None:
    baseline_rows = {
        row["scenarioKey"]: row
        for row in read_rows(BASELINE_CSV)
        if row["caseKey"] == "baseline"
    }
    interval_rows = {
        row["scenarioKey"]: row
        for row in read_rows(BASELINE_INTERVALS_CSV)
        if row["caseKey"] == "baseline" and row["metric"] == "directionalScore"
    }
    lines = [
        "% Auto-generated by paper/scripts/generate_tables.py",
        r"\begin{table}[hbt!]",
        r"\centering",
        r"\caption{Baseline scenario diagnostics.}",
        r"\label{tab:baseline-results}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{@{}lrrrrrrrr@{}}",
        r"\toprule",
        r"Scenario & Score & 95\% CI & Stability & Rights & Shadow $\downarrow$ & Legitimacy & Responsiveness & Cost $\downarrow$ \\",
        r"\midrule",
    ]
    for scenario in SCENARIO_ORDER:
        row = baseline_rows[scenario]
        interval = interval_rows[scenario]
        lines.append(
            " & ".join(
                [
                    SCENARIO_LABELS[scenario],
                    num(row["directionalScore"]),
                    f"{num(interval['lower95'])}--{num(interval['upper95'])}",
                    num(row["legalStability"]),
                    num(row["rightsProtection"]),
                    num(row["shadowDocketAbuse"]),
                    num(row["legitimacy"]),
                    num(row["democraticResponsiveness"]),
                    num(row["totalInstitutionalCost"]),
                ]
            )
            + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\begin{minipage}{0.96\linewidth}",
            r"\footnotesize Notes: Values are baseline campaign estimates. The score column reports the equally weighted directional diagnostic score; the interval column reports the conservative 95\% interval for that score. Lower values are preferable for shadow-docket abuse and institutional cost. Scenario abbreviations match the figure labels.",
            r"\end{minipage}",
            r"\end{table}",
            "",
        ]
    )
    write("baseline_results.tex", "\n".join(lines))


def calibration_lookup() -> dict[tuple[str, str], dict[str, str]]:
    rows: dict[tuple[str, str], dict[str, str]] = {}
    for path in CONFIG_DIR.glob("*.csv"):
        for row in read_rows(path):
            rows[(row["profileKey"], row["targetKey"])] = row
    return rows


def generate_calibration_targets() -> None:
    lookup = calibration_lookup()
    lines = [
        "% Auto-generated by paper/scripts/generate_tables.py",
        r"\begin{table}[hbt!]",
        r"\centering",
        r"\caption{Examples of external calibration targets.}",
        r"\label{tab:calibration-targets}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{@{}p{0.26\linewidth}p{0.27\linewidth}rrrl@{}}",
        r"\toprule",
        r"Court and period & Target & Observed & Range & $n$ & Reliability \\",
        r"\midrule",
    ]
    for _, profile, target in CALIBRATION_ROWS:
        row = lookup[(profile, target)]
        court = f"{row['court']} ({row['timePeriod']})"
        target_label = row["label"]
        observed = num(row["observedValue"])
        target_range = f"{num(row['lowerBound'])}--{num(row['upperBound'])}"
        n = row["n"] if row["n"] and row["n"] != "0" else "--"
        lines.append(
            f"{latex_escape(court)} & {latex_escape(target_label)} & {observed} & {target_range} & {latex_escape(n)} & {latex_escape(row['reliability'])} \\\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\begin{minipage}{0.96\linewidth}",
            r"\footnotesize Notes: The table reports selected calibration targets from the repository's CSV files. Ranges are target intervals, not estimated model effects. Source names, URLs, notes, and validation flags are retained in the replication files.",
            r"\end{minipage}",
            r"\end{table}",
            "",
        ]
    )
    write("calibration_targets.tex", "\n".join(lines))


def main() -> None:
    generate_baseline_results()
    generate_calibration_targets()


if __name__ == "__main__":
    main()
