#!/usr/bin/env python3
"""Publish source-bound historical results without refitting or recomputing estimates."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
EMPIRICAL = "constitutional-review-historical-benchmark-v1"
STUDY = "constitutional-review-historical-robustness-v1"
PROFILES = {
    "frozen-generator": "Fixed generator",
    "recency-weighted-15y": "Recency-weighted",
    "expanding-history": "Expanding history",
    "previous-term": "Previous term",
}
DESIGNS = {
    "current-federal-court": "Current",
    "reasoned-emergency-review": "Reasoned",
    "constitutional-council": "Council",
    "weak-form-review": "Weak form",
    "weak-form-half-response": "Weak form (half)",
    "weak-form-no-response": "Weak form (off)",
}
METRICS = {
    "emergencyReasonGivingRate": "Reasons per order",
    "meritsFollowUpRate": "Merits follow-up",
    "averageTimeToReview": "Review-time input",
    "totalInstitutionalCost": "Total cost index",
    "shadowDocketAbuse": "Emergency irregularity",
    "institutionalDelayCost": "Delay-cost index",
    "directCourtCost": "Direct court cost",
    "upstreamScreeningCost": "Upstream cost",
    "capacityStrainCost": "Capacity strain",
    "intakeAcceptanceRate": "Intake acceptance",
    "councilScreenRate": "Council screening",
    "administrativeLoad": "Administrative load",
    "legislativeResponseRate": "Legislative response",
    "legislativeResponseCredibility": "Response credibility",
    "timelyLegislativeResponseRate": "Timely replies",
    "rightsProtection": "Rights index",
    "complianceRate": "Compliance events",
    "democraticResponsiveness": "Responsiveness",
    "vetoRelocationRisk": "Veto-risk index",
    "averageLegislativeResponseDelay": "Reply delay",
    "legalStability": "Legal stability",
    "legitimacy": "Public-legitimacy proxy",
    "caseSelectionAccess": "Case-selection access",
    "constitutionalConflict": "Conflict index",
}
CONTRASTS = {
    "emergency-base": "Reasoned - current",
    "screening-base": "Council - current",
    "weak-form-base": "Weak form - current",
    "emergency-ablation": "Fast - reasoned",
    "screening-ablation": "Full court - council",
    "weak-form-half": "Half - weak form",
    "weak-form-off": "Off - weak form",
    "weak-form-half-v-current": "Half - current",
    "weak-form-off-v-current": "Off - current",
}
FAMILIES = {"emergency": "Emergency", "screening": "Screening", "weak-form": "Weak form"}


def digest(path):
    with path.open("rb") as handle:
        return hashlib.file_digest(handle, "sha256").hexdigest()


def read_rows(path):
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def escape(value):
    replacements = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
                    "{": r"\{", "}": r"\}", "\\": r"\textbackslash{}"}
    return "".join(replacements.get(char, char) for char in str(value))


def number(value, places=4):
    rounded = round(float(value), places)
    return f"{0.0 if rounded == 0 else rounded:.{places}f}"


def span(row):
    return number(row["pointMin"]) + " to " + number(row["pointMax"])


def table(caption, label, columns, headings, rows, note, *, long=False):
    lines = ["% Auto-generated by paper/scripts/generate_historical_tables.py", r"{\small",
             r"\setlength{\tabcolsep}{3pt}"]
    heading = " & ".join(headings) + r" \\"
    if long:
        lines += [rf"\begin{{longtable}}{{{columns}}}", rf"\caption{{{caption}}}\label{{{label}}}\\",
                  r"\toprule", heading, r"\midrule", r"\endfirsthead", r"\toprule", heading,
                  r"\midrule", r"\endhead"]
    else:
        lines += [r"\begin{table}[hbt!]", r"\centering", rf"\caption{{{caption}}}\label{{{label}}}",
                  rf"\begin{{tabular}}{{{columns}}}", r"\toprule", heading, r"\midrule"]
    lines += [" & ".join(row) + r" \\" for row in rows]
    lines += [r"\bottomrule", r"\end{longtable}" if long else r"\end{tabular}",
              r"\par\noindent\begin{minipage}{0.98\linewidth}\footnotesize " + note + r"\end{minipage}"]
    if not long:
        lines.append(r"\end{table}")
    return "\n".join(lines + ["}", ""]).encode()


def load_evidence(root):
    reports = root / "reports"
    analysis_path = reports / f"{STUDY}-analysis-manifest.json"
    validation_path = reports / f"{STUDY}-analysis-validation.json"
    analysis = json.loads(analysis_path.read_text())
    validation = json.loads(validation_path.read_text())
    lock_path = root / "config/historical-benchmark/first-evaluation-lock.json"
    lock = json.loads(lock_path.read_text())
    inputs = {**analysis["inputSha256"], **lock["sha256"]}
    inputs.update({f"reports/{STUDY}{suffix}": value for suffix, value in analysis["outputSha256"].items()})
    inputs.update({str(path.relative_to(root)): digest(path) for path in (analysis_path, validation_path, lock_path)})
    inputs["scripts/check_historical_analysis.py"] = validation["inputSha256"]["validator"]
    if validation["inputSha256"]["analysisManifest"] != digest(analysis_path):
        raise ValueError("publication analysis validation is stale")
    for relative, expected in inputs.items():
        if digest(root / relative) != expected:
            raise ValueError("publication evidence hash mismatch: " + relative)
    first = json.loads((reports / f"{EMPIRICAL}-first-evaluation.json").read_text())
    forecasts_path = root / "config/historical-benchmark/forecasts-2025.json"
    protocol_path = root / "config/historical-benchmark/protocol-v1.json"
    for path, key in ((forecasts_path, "forecastSha256"), (protocol_path, "protocolSha256")):
        if digest(path) != first["provenance"][key]:
            raise ValueError("publication frozen input mismatch")
        inputs[str(path.relative_to(root))] = digest(path)
    tables = {suffix: read_rows(reports / f"{STUDY}{suffix}") for suffix in analysis["rows"]}
    return first, json.loads(forecasts_path.read_text()), json.loads(protocol_path.read_text()), tables, inputs


def build_artifacts(root=ROOT):
    first, forecasts, protocol, data, inputs = load_evidence(root)
    artifacts = {}
    scores = [[PROFILES[row["model"]], number(row["multiclass-brier"]), number(row["log-loss"]),
               number(row["total-variation"])] for row in first["modelScores"]]
    primary = next(row for row in first["pairedDifferences"] if row["metric"] == "multiclass-brier"
                   and row["comparison"] == "recency-weighted-15y minus frozen-generator")
    note = (f"The {first['targetTerm']} term contains {first['testN']} citation-centered disputes. All scores are lower-is-better. "
            f"Primary recency-minus-fixed Brier difference: {number(primary['difference'], 6)}, paired 95\\% interval "
            f"[{number(primary['lower'], 6)}, {number(primary['upper'], 6)}]. "
            "This is within-term, fixed-forecast uncertainty, not between-term uncertainty. "
            "The first evaluation is retained; no clear conditional advantage is established.")
    artifacts["historical_scores.tex"] = table("Frozen 2025 docket-composition evaluation.", "tab:historical-scores",
        r"@{}L{0.36\linewidth}rrr@{}", ["Forecast", "Brier", "Log loss", "Total variation"], scores, note)
    patterns = {(row["contrast"], row["metric"]): row for row in data["-component-patterns.csv"]}
    def bounds(contrast, metric):
        return span(patterns[(contrast, metric)])
    claim_rows = [
        ["Emergency", "Irregularity: " + bounds("emergency-base", "shadowDocketAbuse") + "; total cost: "
         + bounds("emergency-base", "totalInstitutionalCost") + ".",
         "Lower irregularity; higher cost. Shared review-time input cannot identify procedural duration. "
         "Reasons per order require the empty-denominator caveat."],
        ["Screening", "Council upstream cost: " + bounds("screening-base", "upstreamScreeningCost")
         + "; full-court structure intervention: " + bounds("screening-ablation", "upstreamScreeningCost") + ".",
         "Both are below the 0.01 practical threshold throughout. This intervention does not establish substantial upstream displacement."],
        ["Weak form", "Response-off minus full responsiveness: " + bounds("weak-form-off", "democraticResponsiveness")
         + "; veto risk: " + bounds("weak-form-off", "vetoRelocationRisk") + ".",
         "Response dependence is partial. Compliance and cost advantages over current persist even with responses disabled."],
    ]
    artifacts["historical_claims.tex"] = table("Three institutional claims after the historical robustness study.",
        "tab:historical-claims", r"@{}L{0.13\linewidth}L{0.36\linewidth}L{0.43\linewidth}@{}",
        ["Claim", "Paired difference range", "Qualified conclusion"], claim_rows,
        "Ranges span 52 fixed forecast/context cells, not confidence intervals. Base contrasts are reasoned or council minus current; "
        "ablations are changed design minus its parent. Outputs are model indices/events, not identified reform effects.")
    claim_rows = []
    for row in data["-claim-matrix.csv"]:
        marker = r"$^\dagger$" if row["role"] == "additional-diagnostic" else ""
        claim_rows.append([FAMILIES[row["claim"]], METRICS[row["metric"]] + marker, span(row),
                           escape(row["classification"]), f"{row['intervalsAboveZero']}/{row['intervalsBelowZero']}"])
    artifacts["supplement_historical_claims.tex"] = table("Complete component-level claim matrix.", "tab:supp-historical-claims",
        r"@{}L{0.12\linewidth}L{0.25\linewidth}L{0.21\linewidth}L{0.19\linewidth}r@{}",
        ["Claim", "Component", "Difference range", "Pattern", "CI +/$-$"], claim_rows,
        r"All 22 components are shown. $\dagger$ Additional diagnostics, not replacement endpoints. "
        "Stable requires every signed base estimate beyond the expected strict 0.01 threshold; sign-reversing requires both practical signs. "
        "Unsigned rows are descriptive-only. CI counts are unadjusted intervals above/below zero, out of 52. "
        "Duration is a shared input; conditional reasons, follow-up and reply timing depend on eligible-event populations. "
        "Mechanism activation and constructed indices are not independent validation.", long=True)
    ablation_rows = [[CONTRASTS[row["contrast"]], METRICS[row["metric"]], span(row),
                      f"{row['intervalsAboveZero']}/{row['intervalsBelowZero']}"]
                     for row in data["-component-patterns.csv"] if row["kind"] != "base"]
    artifacts["supplement_historical_ablations.tex"] = table("All mechanism and persistence contrasts.", "tab:supp-historical-ablations",
        r"@{}L{0.26\linewidth}L{0.27\linewidth}L{0.24\linewidth}r@{}",
        ["Contrast", "Component", "Difference range", "CI +/$-$"], ablation_rows,
        "Ranges span the same 52 cells. Fast changes only emergency procedure; full court changes only council review structure. "
        "Half/off scale response credibility and thin positive response events. Half/off minus current are persistence checks. "
        "No replies is not a late or instantaneous reply; reply-conditioned comparisons are not population-matched.", long=True)
    interval_rows = [[CONTRASTS[row["contrast"]], METRICS[row["metric"]], number(row["difference"]),
                      f"[{number(row['lower'])}, {number(row['upper'])}]"]
                     for row in data["-contrasts.csv"] if row["profile"] == "frozen-generator" and row["context"] == "baseline"]
    artifacts["supplement_historical_intervals.tex"] = table("Paired intervals in the fixed-generator, baseline-context cell.",
        "tab:supp-historical-intervals", r"@{}L{0.25\linewidth}L{0.25\linewidth}rL{0.26\linewidth}@{}",
        ["Contrast", "Component", "Difference", "95\\% MC interval"], interval_rows,
        "All 71 component/contrast combinations in this reference cell are shown without significance filtering. "
        "The CSV retains all 3,692 estimates, intervals and Monte Carlo standard errors. Intervals use 2,000 paired whole-run "
        "bootstrap draws over 120 runs; they do not measure structural or normative uncertainty.", long=True)
    leadership = data["-leadership.csv"]
    leadership_rows = []
    for variant in ("full-response", "half-response", "no-response"):
        for scenario in dict.fromkeys(row["scenario"] for row in leadership if row["responseVariant"] == variant):
            values = [float(row["leadershipShare"]) for row in leadership if row["responseVariant"] == variant and row["scenario"] == scenario]
            leadership_rows.append([variant.replace("-", " "), DESIGNS[scenario], f"{min(values):.1%} to {max(values):.1%}".replace("%", r"\%")])
    reversing = sum(row["reversesAcrossWeights"] == "True" for row in data["-preference-pairs.csv"])
    artifacts["supplement_historical_leadership.tex"] = table("Normative leadership across the registered grid.", "tab:supp-historical-leadership",
        r"@{}L{0.28\linewidth}L{0.32\linewidth}L{0.25\linewidth}@{}", ["Response setting", "Design", "Leadership range"], leadership_rows,
        "Minimum/maximum shares across 52 cells using the same 1,000 Dirichlet preference vectors. Each competition has four designs; "
        f"only weak form is replaced. {reversing} of 312 base pair/cell comparisons reverse across weights. "
        "Ties within $10^{-12}$ split credit. These are illustrative preferences, not probabilities that an institution is optimal.", long=True)
    denominator_rows = []
    for row in data["-conditional-denominators.csv"]:
        if row["context"] == "emergencyPressure-low" and row["scenario"] in protocol["stressScenarioKeys"][:2]:
            denominator_rows.append([PROFILES[row["profile"]], DESIGNS[row["scenario"]], row["emergencyOrders"],
                                     row["ordersWithReasons"], row["runsWithoutEmergencyOrders"],
                                     number(row["pooledReasonsPerOrder"]) if row["pooledReasonsPerOrder"] else "NA"])
    artifacts["supplement_historical_denominators.tex"] = table("Low-emergency reason-giving denominators.", "tab:supp-historical-denominators",
        r"@{}L{0.24\linewidth}L{0.14\linewidth}rrrr@{}", ["Forecast", "Design", "Orders", "Reasons", "Empty runs", "Pooled rate"], denominator_rows,
        "Each row covers 120 runs. Legacy no-order run rates equal zero. Pooled reasons per order are post-estimate diagnostics, "
        "not replacement primary estimands; sparse counts cannot establish a reliable conditional comparison. "
        "An empty pooled denominator is NA, not an observed zero.", long=True)
    secondary_rows = [[escape(row["comparison"].replace("recency-weighted-15y minus ", "Recency - ").replace("frozen-generator", "fixed")
                              .replace("expanding-history", "expanding").replace("previous-term", "previous")),
                       escape(row["metric"]), number(row["difference"], 6),
                       f"[{number(row['lower'], 6)}, {number(row['upper'], 6)}]"] for row in first["pairedDifferences"]]
    artifacts["supplement_historical_scores.tex"] = table("All frozen empirical paired-score comparisons.", "tab:supp-historical-scores",
        r"@{}L{0.25\linewidth}L{0.21\linewidth}rL{0.28\linewidth}@{}", ["Comparison", "Score", "Difference", "95\\% interval"], secondary_rows,
        "All scores are lower-is-better. The primary endpoint is recency-minus-fixed Brier score. "
        "Secondary advantages against the previous-term baseline do not replace that endpoint. "
        "Paired-case bootstrap uncertainty holds the forecasts fixed within the 66-dispute term.", long=True)
    context_rows = [[escape(name), str(values[0]), str(values[1])] for name, values in protocol["contextOneAtATime"].items()]
    artifacts["supplement_historical_contexts.tex"] = table("One-at-a-time context grid.", "tab:supp-historical-contexts",
        r"@{}L{0.55\linewidth}rr@{}", ["World input", "Low", "High"], context_rows,
        "Baseline plus twelve one-at-a-time settings gives thirteen contexts per forecast. Other world inputs remain at their baseline values. "
        "This finite grid assigns no probability to real political environments and is not a full interaction design.", long=True)
    # Keep all eight categories and the residual denominator visible. The forecast file is source-hashed above.
    category_rows = [[escape(row["category"].replace("_", " ").title()), str(row["count"]), number(row["share"])] for row in first["categories"]]
    artifacts["supplement_historical_categories.tex"] = table("Observed 2025 test categories, without denominator exclusions.",
        "tab:supp-historical-categories", r"@{}L{0.55\linewidth}rr@{}", ["Category", "Disputes", "Share"], category_rows,
        "The eight categories form a mutually exclusive partition of all 66 citation-centered disputes. "
        "Other remains in the denominator. Observed test shares were not used as simulation profiles; "
        "the four simulation profiles are the training-only forecasts retained in the replication inputs.", long=True)
    forecast_rows = [[escape(category.replace("_", " ").title())]
                     + [number(forecast["probabilities"][index]) for forecast in forecasts["forecasts"]]
                     for index, category in enumerate(forecasts["categories"])]
    artifacts["supplement_historical_forecasts.tex"] = table("Locked training-only forecast probabilities.", "tab:supp-historical-forecasts",
        r"@{}L{0.33\linewidth}rrrr@{}", ["Category", "Fixed", "Recency", "Expanding", "Previous"], forecast_rows,
        "Probabilities are displayed rounded; full precision is retained in the frozen JSON. Recency uses 2010--2024 (1,059 disputes); "
        "expanding uses 1946--2024 (9,341); previous uses 2024 (64). The fixed vector was already informed by legacy aggregate calibration. "
        "The test categories in the preceding table are never substituted into these profiles.", long=True)
    weight_rows = [[METRICS[higher], METRICS[lower]] for higher, lower in zip(protocol["weightMetricsHigher"], protocol["weightMetricsLower"])]
    artifacts["supplement_historical_weights.tex"] = table("Metric directions in the new normative exercise.", "tab:supp-historical-weights",
        r"@{}L{0.44\linewidth}L{0.44\linewidth}@{}", ["Higher-is-better", "Lower-is-better"], weight_rows,
        "Metric order is the higher-is-better column followed by the lower-is-better column. "
        "Only the latter is transformed to $1-x$. No observed-grid normalization is fitted. "
        "The review-time input is shared, so its weighted term cannot distinguish designs within a cell.", long=True)
    cost_rows = []
    for prefix, label in (("directOnly", "Direct-only view"), ("fullAccounting", "Full accounting"),
                          ("fullMinusDirectContrast", "Full minus direct contrast")):
        values = [float(row[prefix + "Difference"]) for row in data["-cost-accounting.csv"]]
        cost_rows.append([label, number(min(values)) + " to " + number(max(values))])
    changes = sum(row["practicalSignChange"] == "True" for row in data["-cost-accounting.csv"])
    artifacts["supplement_historical_accounting.tex"] = table("Council-minus-current accounting-view sensitivity.", "tab:supp-historical-accounting",
        r"@{}L{0.47\linewidth}L{0.35\linewidth}@{}", ["Accounting contrast", "Difference range"], cost_rows,
        f"Direct-only versus full accounting changes the practical sign in {changes} of 52 cells. "
        "These are differently constructed normalized indices, not additive monetary costs. Full per-cell paired intervals and "
        "the paired difference-of-contrasts are retained in the cost-accounting CSV.", long=True)
    inputs["paper/scripts/generate_historical_tables.py"] = digest(Path(__file__))
    manifest = {"purpose": "publication projection of immutable empirical and source-hashed institutional evidence",
                "inputSha256": inputs, "outputSha256": {name: hashlib.sha256(content).hexdigest() for name, content in artifacts.items()},
                "coverage": {"claimComponents": len(claim_rows), "ablationAndPersistenceComponents": len(ablation_rows),
                             "referenceCellIntervals": len(interval_rows), "empiricalPairedScores": len(secondary_rows)}}
    artifacts["historical-publication-manifest.json"] = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()
    return artifacts


def generate(root=ROOT, *, check=False):
    artifacts = build_artifacts(root)
    directory = root / "paper/tables"
    for name, content in artifacts.items():
        path = directory / name
        if check:
            if not path.exists() or path.read_bytes() != content:
                raise ValueError("historical publication artifact is stale: " + name)
        else:
            directory.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    return len(artifacts)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    print(f"{'Verified' if args.check else 'Generated'} {generate(check=args.check)} historical publication artifacts.")


if __name__ == "__main__":
    main()
