#!/usr/bin/env python3
"""Generate portable LaTeX figure fragments from constitutional-review reports."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPORT_DIR = ROOT / "reports"
FIGURE_DIR = ROOT / "paper" / "figures"
BASELINE_CSV = REPORT_DIR / "constitutional-review-campaign-v0.csv"
PAIRED_CSV = REPORT_DIR / "constitutional-review-paired-import-v1.csv"

SCENARIO_LABELS = {
    "current-federal-court": "CUR",
    "eighteen-year-terms": "18Y",
    "fifteen-justice-commission": "15J",
    "supermajority-invalidation": "SUP",
    "strict-recusal-court": "REC",
    "reasoned-emergency-review": "EMR",
    "panel-en-banc-review": "PAN",
    "dual-cross-checking-courts": "DUAL",
    "constitutional-council": "COUNC",
    "legislative-override-court": "OVR",
    "accountability-retention-court": "RET",
    "independence-accountability-hybrid": "HYB",
    "weak-form-review": "WFR",
    "suspended-declaration-review": "SUS",
    "override-clause-review": "OVC",
    "pre-enactment-review": "PRE",
    "abstract-review-tribunal": "ABS",
    "ombudsman-triggered-review": "OMB",
    "constitutional-public-defender": "DEF",
    "rights-impact-statement-review": "RIS",
    "mandatory-legislative-response": "MLR",
}

BASELINE_SCATTER_SCENARIOS = [
    "current-federal-court",
    "reasoned-emergency-review",
    "dual-cross-checking-courts",
    "constitutional-council",
    "legislative-override-court",
    "independence-accountability-hybrid",
    "weak-form-review",
    "suspended-declaration-review",
    "pre-enactment-review",
    "abstract-review-tribunal",
    "ombudsman-triggered-review",
    "constitutional-public-defender",
    "rights-impact-statement-review",
    "mandatory-legislative-response",
]

MECHANISM_SCENARIOS = [
    "weak-form-review",
    "suspended-declaration-review",
    "override-clause-review",
    "pre-enactment-review",
    "abstract-review-tribunal",
    "ombudsman-triggered-review",
    "constitutional-public-defender",
    "rights-impact-statement-review",
    "mandatory-legislative-response",
]

EMERGENCY_SCENARIOS = [
    "current-federal-court",
    "strict-recusal-court",
    "reasoned-emergency-review",
    "dual-cross-checking-courts",
    "constitutional-council",
    "independence-accountability-hybrid",
]

PAIRED_SCENARIOS = [
    ("current-federal-court", "black"),
    ("reasoned-emergency-review", "black!70"),
    ("dual-cross-checking-courts", "black!45"),
    ("constitutional-council", "black!30"),
    ("independence-accountability-hybrid", "black!55"),
    ("weak-form-review", "black!40"),
    ("mandatory-legislative-response", "black!60"),
]

PAIRED_LABEL_OFFSETS = {
    "current-federal-court": -1.0,
    "reasoned-emergency-review": -1.0,
    "dual-cross-checking-courts": 3.0,
    "constitutional-council": 1.0,
    "independence-accountability-hybrid": -1.5,
    "weak-form-review": 2.5,
    "mandatory-legislative-response": -2.5,
}

PAIRED_CASES = [
    ("synthetic-baseline", "SB"),
    ("legislative-all", "ALL"),
    ("legislative-high-capture", "CAP"),
    ("legislative-high-volatility", "VOL"),
    ("legislative-low-mandate", "MAND"),
]


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def baseline_rows() -> list[dict[str, str]]:
    return [row for row in read_rows(BASELINE_CSV) if row["caseKey"] == "baseline"]


def row_float(row: dict[str, str], field: str) -> float:
    return float(row[field])


def coord(value: float, lower: float, upper: float, start: float, length: float) -> float:
    if upper == lower:
        return start + (length / 2.0)
    return start + ((value - lower) / (upper - lower)) * length


def write(name: str, content: str) -> None:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    (FIGURE_DIR / name).write_text(content, encoding="utf-8")


def fmt(value: float) -> str:
    return f"{value:.1f}"


def sign(value: float) -> int:
    if value > 0:
        return 1
    if value < 0:
        return -1
    return 0


def figure_label(key: str) -> str:
    label = SCENARIO_LABELS[key]
    return f"{label}*" if key == "current-federal-court" else label


def leader_line(
        start_x: float,
        start_y: float,
        end_x: float,
        end_y: float,
        color: str = "black!55",
        samples: int = 10,
) -> str:
    mid_x = (start_x + end_x) / 2.0
    mid_y = (start_y + end_y) / 2.0
    return (
        rf"{{\color{{{color}}}\qbezier[{samples}]"
        rf"({fmt(start_x)},{fmt(start_y)})"
        rf"({fmt(mid_x)},{fmt(mid_y)})"
        rf"({fmt(end_x)},{fmt(end_y)})}}"
    )


def generate_model_pipeline() -> None:
    write(
        "model_pipeline.tex",
        r"""% Auto-generated by paper/scripts/generate_figures.py
\begingroup
\setlength{\unitlength}{1mm}
\begin{picture}(128,66)
\scriptsize
\put(2,45){\framebox(22,12){\shortstack[c]{Scenario\\catalog}}}
\put(28,45){\framebox(22,12){\shortstack[c]{World and\\case generation}}}
\put(54,45){\framebox(22,12){\shortstack[c]{Institutional\\routing}}}
\put(80,45){\framebox(22,12){\shortstack[c]{Decision\\process}}}
\put(106,45){\framebox(20,12){\shortstack[c]{Outputs\\and reports}}}
\put(24,51){\vector(1,0){4}}
\put(50,51){\vector(1,0){4}}
\put(76,51){\vector(1,0){4}}
\put(102,51){\vector(1,0){4}}
\put(28,26){\framebox(22,10){\shortstack[c]{Legislative\\outputs}}}
\put(39,36){\vector(0,1){9}}
\put(54,28){\framebox(22,10){\shortstack[c]{Intake and\\access filters}}}
\put(80,28){\framebox(22,10){\shortstack[c]{Emergency\\and merits}}}
\put(106,28){\framebox(20,10){\shortstack[c]{Compliance\\reaction cost}}}
\put(50,33){\vector(1,0){4}}
\put(76,33){\vector(1,0){4}}
\put(102,33){\vector(1,0){4}}
\put(116,28){\vector(0,-1){8}}
\put(64,12){\framebox(38,8){\shortstack[c]{Period turnover and\\political-culture state}}}
\put(64,16){\vector(-1,0){40}}
\put(83,20){\vector(0,1){8}}
\put(13,38){\makebox(0,0){\shortstack[c]{appointment, size, tenure,\\thresholds, councils, overrides}}}
\put(115,19){\makebox(0,0){\shortstack[c]{direct outputs, composites,\\uncertainty, provenance}}}
\put(64,5){\makebox(0,0){\shortstack[c]{Case generation, routing, decisions, compliance, reaction, and scoring are separate audit points.}}}
\end{picture}
\endgroup
""",
    )


def generate_emergency_bars(rows: list[dict[str, str]]) -> None:
    by_key = {row["scenarioKey"]: row for row in rows}
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        r"\begingroup",
        r"\setlength{\unitlength}{1mm}",
        r"\begin{picture}(128,72)",
        r"\scriptsize",
    ]
    left, width = 36.0, 78.0
    y_top, gap = 56.0, 8.0
    for tick in [0.0, 0.25, 0.5, 0.75, 1.0]:
        x = left + (tick * width)
        lines.append(rf"\put({fmt(x)},10){{\color{{black!15}}\line(0,1){{50}}}}")
        label = "1" if tick == 1.0 else ("0" if tick == 0.0 else f"{tick:.2f}".rstrip("0"))
        lines.append(rf"\put({fmt(x)},6){{\makebox(0,0){{{label}}}}}")
    lines.append(rf"\put({fmt(left)},10){{\line(1,0){{{fmt(width)}}}}}")
    lines.append(rf"\put({fmt(left)},10){{\line(0,1){{50}}}}")
    lines.append(r"\put(36,64){\color{black}\rule{6mm}{1.2mm}}")
    lines.append(r"\put(44,64){\makebox(0,0)[l]{emergency irregularity}}")
    lines.append(r"\put(76,64){\color{black!55}\rule{6mm}{1.2mm}}")
    lines.append(r"\put(84,64){\makebox(0,0)[l]{reason-giving}}")
    lines.append(r"\put(36,60.5){\color{black!25}\rule{6mm}{1.2mm}}")
    lines.append(r"\put(44,60.5){\makebox(0,0)[l]{merits follow-up}}")
    for i, key in enumerate(EMERGENCY_SCENARIOS):
        row = by_key[key]
        y = y_top - (i * gap)
        label = figure_label(key)
        lines.append(rf"\put(32,{fmt(y)}){{\makebox(0,0)[r]{{{label}}}}}")
        for offset, field, color in [
            (1.8, "shadowDocketAbuse", "black"),
            (0.0, "emergencyReasonGivingRate", "black!55"),
            (-1.8, "meritsFollowUpRate", "black!25"),
        ]:
            bar = row_float(row, field) * width
            lines.append(rf"\put({fmt(left)},{fmt(y + offset)}){{\color{{{color}}}\rule{{{fmt(bar)}mm}}{{1.2mm}}}}")
    lines.append(r"\put(75,2){\makebox(0,0){rate}}")
    lines.extend([r"\end{picture}", r"\endgroup", ""])
    write("emergency_docket_bars.tex", "\n".join(lines))


def generate_cost_score_scatter(rows: list[dict[str, str]]) -> None:
    rows = [row for row in rows if row["scenarioKey"] in BASELINE_SCATTER_SCENARIOS]
    left, bottom, width, height = 22.0, 15.0, 92.0, 58.0
    x_min, x_max = 0.25, 0.65
    y_min, y_max = 0.60, 0.78
    offsets = {
        "CUR": (-3.4, 5.2, "r"),
        "EMR": (7.5, 12.0, "l"),
        "DUAL": (3.2, 2.0, "l"),
        "COUNC": (-0.5, 6.0, "c"),
        "OVR": (5.4, -6.6, "l"),
        "HYB": (4.0, 4.0, "l"),
        "WFR": (-4.4, 4.2, "r"),
        "SUS": (7.4, -8.8, "l"),
        "PRE": (-7.0, 2.0, "r"),
        "ABS": (4.0, 2.6, "l"),
        "OMB": (4.0, -5.0, "l"),
        "DEF": (-4.0, -5.0, "r"),
        "RIS": (-4.0, 2.8, "r"),
        "MLR": (8.0, 7.5, "l"),
    }
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        r"\begingroup",
        r"\setlength{\unitlength}{1mm}",
        r"\begin{picture}(128,86)",
        r"\scriptsize",
    ]
    for tick in [0.30, 0.40, 0.50, 0.60]:
        x = coord(tick, x_min, x_max, left, width)
        lines.append(rf"\put({fmt(x)},{fmt(bottom)}){{\color{{black!15}}\line(0,1){{{fmt(height)}}}}}")
        lines.append(rf"\put({fmt(x)},{fmt(bottom - 4)}){{\makebox(0,0){{{tick:.2f}}}}}")
    for tick in [0.60, 0.65, 0.70, 0.75]:
        y = coord(tick, y_min, y_max, bottom, height)
        lines.append(rf"\put({fmt(left)},{fmt(y)}){{\color{{black!15}}\line(1,0){{{fmt(width)}}}}}")
        lines.append(rf"\put({fmt(left - 4)},{fmt(y)}){{\makebox(0,0)[r]{{{tick:.2f}}}}}")
    lines.append(rf"\put({fmt(left)},{fmt(bottom)}){{\line(1,0){{{fmt(width)}}}}}")
    lines.append(rf"\put({fmt(left)},{fmt(bottom)}){{\line(0,1){{{fmt(height)}}}}}")
    lines.append(r"\put(26,79){\makebox(0,0)[l]{\rule{1.8mm}{1.8mm} court architecture \quad \raisebox{-0.3mm}{\framebox(1.8,1.8){}} mechanism scenario}}")
    for row in rows:
        key = row["scenarioKey"]
        label = SCENARIO_LABELS[key]
        x = coord(row_float(row, "totalInstitutionalCost"), x_min, x_max, left, width)
        y = coord(row_float(row, "democraticConstitutionalism"), y_min, y_max, bottom, height)
        color = "black"
        size = 2.1 if key == "current-federal-court" else 1.7
        if row.get("scenarioKind") == "synthetic_mechanism":
            lines.append(rf"\put({fmt(x - size / 2.0)},{fmt(y - size / 2.0)}){{\color{{{color}}}\framebox({fmt(size)},{fmt(size)}){{}}}}")
        else:
            lines.append(rf"\put({fmt(x)},{fmt(y)}){{\makebox(0,0){{\color{{{color}}}\rule{{{size}mm}}{{{size}mm}}}}}}")
        dx, dy, align = offsets[label]
        line_start_x = x + (sign(dx) * (size / 2.0 + 0.4))
        line_start_y = y + (sign(dy) * (size / 2.0 + 0.4))
        label_x = x + dx
        label_y = y + dy
        if abs(dx) >= 3.5 or abs(dy) >= 3.5:
            label_edge_x = label_x
            if align == "l":
                label_edge_x -= 0.9
            elif align == "r":
                label_edge_x += 0.9
            lines.append(leader_line(line_start_x, line_start_y, label_edge_x, label_y, "black!45", 8))
        lines.append(rf"\put({fmt(x + dx)},{fmt(y + dy)}){{\makebox(0,0)[{align}]{{{figure_label(key)}}}}}")
    lines.append(r"\put(68,4){\makebox(0,0){total institutional cost}}")
    lines.append(r"\put(4,45){\rotatebox{90}{\makebox(0,0){democratic constitutionalism}}}")
    lines.extend([r"\end{picture}", r"\endgroup", ""])
    write("cost_score_scatter.tex", "\n".join(lines))


def generate_mechanism_tradeoff(rows: list[dict[str, str]]) -> None:
    rows = [row for row in rows if row["scenarioKey"] in MECHANISM_SCENARIOS]
    left, bottom, width, height = 22.0, 15.0, 92.0, 58.0
    x_min, x_max = 0.00, 0.55
    y_min, y_max = 0.58, 0.78
    offsets = {
        "WFR": (-4.0, 4.8, "r"),
        "SUS": (4.0, -4.4, "l"),
        "OVC": (4.0, 4.6, "l"),
        "PRE": (-4.0, -4.8, "r"),
        "ABS": (4.2, 1.0, "l"),
        "OMB": (4.2, -4.8, "l"),
        "DEF": (-4.2, -4.8, "r"),
        "RIS": (-4.2, 4.8, "r"),
        "MLR": (4.0, 4.8, "l"),
    }
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        r"\begingroup",
        r"\setlength{\unitlength}{1mm}",
        r"\begin{picture}(128,86)",
        r"\scriptsize",
    ]
    for tick in [0.0, 0.15, 0.30, 0.45]:
        x = coord(tick, x_min, x_max, left, width)
        lines.append(rf"\put({fmt(x)},{fmt(bottom)}){{\color{{black!15}}\line(0,1){{{fmt(height)}}}}}")
        lines.append(rf"\put({fmt(x)},{fmt(bottom - 4)}){{\makebox(0,0){{{tick:.2f}}}}}")
    for tick in [0.60, 0.65, 0.70, 0.75]:
        y = coord(tick, y_min, y_max, bottom, height)
        lines.append(rf"\put({fmt(left)},{fmt(y)}){{\color{{black!15}}\line(1,0){{{fmt(width)}}}}}")
        lines.append(rf"\put({fmt(left - 4)},{fmt(y)}){{\makebox(0,0)[r]{{{tick:.2f}}}}}")
    lines.append(rf"\put({fmt(left)},{fmt(bottom)}){{\line(1,0){{{fmt(width)}}}}}")
    lines.append(rf"\put({fmt(left)},{fmt(bottom)}){{\line(0,1){{{fmt(height)}}}}}")
    for row in rows:
        key = row["scenarioKey"]
        label = SCENARIO_LABELS[key]
        x = coord(row_float(row, "vetoRelocationRisk"), x_min, x_max, left, width)
        y = coord(row_float(row, "democraticConstitutionalism"), y_min, y_max, bottom, height)
        lines.append(rf"\put({fmt(x)},{fmt(y)}){{\makebox(0,0){{\color{{black}}\rule{{1.8mm}}{{1.8mm}}}}}}")
        dx, dy, align = offsets[label]
        lines.append(leader_line(x + sign(dx) * 1.2, y + sign(dy) * 1.2, x + dx, y + dy, "black!45", 8))
        lines.append(rf"\put({fmt(x + dx)},{fmt(y + dy)}){{\makebox(0,0)[{align}]{{{label}}}}}")
    lines.append(r"\put(68,4){\makebox(0,0){veto-relocation risk}}")
    lines.append(r"\put(4,45){\rotatebox{90}{\makebox(0,0){democratic constitutionalism}}}")
    lines.extend([r"\end{picture}", r"\endgroup", ""])
    write("mechanism_tradeoff_scatter.tex", "\n".join(lines))


def generate_paired_lines() -> None:
    rows = read_rows(PAIRED_CSV)
    values = {
        (row["caseKey"], row["scenarioKey"]): row_float(row, "directionalScore")
        for row in rows
    }
    left, bottom, width, height = 24.0, 14.0, 82.0, 58.0
    y_min, y_max = 0.50, 0.84
    x_positions = [
        left + (idx * (width / (len(PAIRED_CASES) - 1)))
        for idx in range(len(PAIRED_CASES))
    ]
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        r"\begingroup",
        r"\setlength{\unitlength}{1mm}",
        r"\begin{picture}(128,88)",
        r"\scriptsize",
    ]
    for tick in [0.50, 0.60, 0.70, 0.80]:
        y = coord(tick, y_min, y_max, bottom, height)
        lines.append(rf"\put({fmt(left)},{fmt(y)}){{\color{{black!15}}\line(1,0){{{fmt(width)}}}}}")
        lines.append(rf"\put({fmt(left - 4)},{fmt(y)}){{\makebox(0,0)[r]{{{tick:.2f}}}}}")
    for x, (_, label) in zip(x_positions, PAIRED_CASES):
        lines.append(rf"\put({fmt(x)},{fmt(bottom)}){{\color{{black!12}}\line(0,1){{{fmt(height)}}}}}")
        lines.append(rf"\put({fmt(x)},{fmt(bottom - 4)}){{\makebox(0,0){{{label}}}}}")
    lines.append(rf"\put({fmt(left)},{fmt(bottom)}){{\line(1,0){{{fmt(width)}}}}}")
    lines.append(rf"\put({fmt(left)},{fmt(bottom)}){{\line(0,1){{{fmt(height)}}}}}")
    scenario_points: dict[str, list[tuple[float, float]]] = {}
    for scenario_key, color in PAIRED_SCENARIOS:
        points: list[tuple[float, float]] = []
        for x, (case_key, _) in zip(x_positions, PAIRED_CASES):
            y = coord(values[(case_key, scenario_key)], y_min, y_max, bottom, height)
            points.append((x, y))
        scenario_points[scenario_key] = points
        lines.append(r"\linethickness{0.35mm}")
        for (x1, y1), (x2, y2) in zip(points, points[1:]):
            mid_x = (x1 + x2) / 2.0
            mid_y = (y1 + y2) / 2.0
            lines.append(rf"{{\color{{{color}}}\qbezier[22]({fmt(x1)},{fmt(y1)})({fmt(mid_x)},{fmt(mid_y)})({fmt(x2)},{fmt(y2)})}}")
        lines.append(r"\linethickness{0.25mm}")
        for x, y in points:
            lines.append(rf"\put({fmt(x)},{fmt(y)}){{\makebox(0,0){{\color{{{color}}}\rule{{1.5mm}}{{1.5mm}}}}}}")
    label_targets = []
    for scenario_key, _ in PAIRED_SCENARIOS:
        end_y = scenario_points[scenario_key][-1][1]
        target = end_y + PAIRED_LABEL_OFFSETS.get(scenario_key, 0.0)
        target = max(bottom + 4.0, min(bottom + height - 4.0, target))
        label_targets.append((target, scenario_key))
    label_targets.sort()
    label_positions: dict[str, float] = {}
    min_gap = 5.5
    previous = bottom + 3.0 - min_gap
    for target, scenario_key in label_targets:
        label_positions[scenario_key] = max(target, previous + min_gap)
        previous = label_positions[scenario_key]
    overflow = max(label_positions.values()) - (bottom + height - 3.0)
    if overflow > 0:
        for scenario_key in label_positions:
            label_positions[scenario_key] -= overflow
    for scenario_key, color in PAIRED_SCENARIOS:
        end_x, end_y = scenario_points[scenario_key][-1]
        label_x = end_x + 4.0
        label_y = label_positions[scenario_key]
        lines.append(leader_line(end_x + 1.1, end_y, label_x - 1.0, label_y, "black!55", 10))
        lines.append(rf"\put({fmt(label_x)},{fmt(label_y)}){{\makebox(0,0)[l]{{\color{{black}}{figure_label(scenario_key)}}}}}")
    lines.append(r"\put(65,4){\makebox(0,0){docket source}}")
    lines.append(r"\put(12,75){\makebox(0,0){score}}")
    lines.append(r"\put(65,80){\makebox(0,0){SB generated; ALL all imports; CAP high capture; VOL high volatility; MAND low mandate}}")
    lines.extend([r"\end{picture}", r"\endgroup", ""])
    write("paired_import_lines.tex", "\n".join(lines))


def main() -> None:
    rows = baseline_rows()
    generate_model_pipeline()
    generate_emergency_bars(rows)
    generate_cost_score_scatter(rows)
    generate_mechanism_tradeoff(rows)
    generate_paired_lines()


if __name__ == "__main__":
    main()
