#!/usr/bin/env python3
"""Generate compact LaTeX tables for the supplementary appendix."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPORT_DIR = ROOT / "reports"
TABLE_DIR = ROOT / "paper" / "tables"
CALIBRATION_SOURCE = ROOT / "config" / "calibration-source-observations.csv"


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def latex_escape(value: str) -> str:
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    return "".join(replacements.get(char, char) for char in value)


def num(value: str | float) -> str:
    return f"{float(value):.3f}"


def write(name: str, content: str) -> None:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    (TABLE_DIR / name).write_text(content, encoding="utf-8")


def scenario_matrix() -> None:
    rows = read_rows(REPORT_DIR / "constitutional-review-campaign-v0.csv")
    lines = [
        "% Auto-generated by paper/scripts/generate_supplement.py",
        r"\begin{longtable}{@{}L{0.18\linewidth}L{0.24\linewidth}rrrrr@{}}",
        r"\caption{Full starter-campaign scenario matrix.}\label{tab:supp-scenario-matrix}\\",
        r"\toprule",
        r"Case & Scenario & Score & Rights & Shadow $\downarrow$ & Legitimacy & Cost $\downarrow$ \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Case & Scenario & Score & Rights & Shadow $\downarrow$ & Legitimacy & Cost $\downarrow$ \\",
        r"\midrule",
        r"\endhead",
    ]
    for row in rows:
        lines.append(
            " & ".join(
                [
                    latex_escape(row["caseName"]),
                    latex_escape(row["scenario"]),
                    num(row["directionalScore"]),
                    num(row["rightsProtection"]),
                    num(row["shadowDocketAbuse"]),
                    num(row["legitimacy"]),
                    num(row["totalInstitutionalCost"]),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{longtable}", ""])
    write("supplement_scenario_matrix.tex", "\n".join(lines))


def sensitivity_matrix() -> None:
    rows = read_rows(REPORT_DIR / "constitutional-review-sensitivity-v1.csv")
    lines = [
        "% Auto-generated by paper/scripts/generate_supplement.py",
        r"\begin{longtable}{@{}L{0.22\linewidth}L{0.24\linewidth}rrrr@{}}",
        r"\caption{Sensitivity-campaign diagnostic matrix.}\label{tab:supp-sensitivity}\\",
        r"\toprule",
        r"Stress case & Scenario & Score & Stability & Conflict $\downarrow$ & Trust \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Stress case & Scenario & Score & Stability & Conflict $\downarrow$ & Trust \\",
        r"\midrule",
        r"\endhead",
    ]
    for row in rows:
        lines.append(
            " & ".join(
                [
                    latex_escape(row["caseName"]),
                    latex_escape(row["scenario"]),
                    num(row["directionalScore"]),
                    num(row["legalStability"]),
                    num(row["constitutionalConflict"]),
                    num(row["publicTrust"]),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{longtable}", ""])
    write("supplement_sensitivity_matrix.tex", "\n".join(lines))


def artifact_inventory() -> None:
    paths = sorted(REPORT_DIR.glob("constitutional-review-*.csv")) + sorted(REPORT_DIR.glob("constitutional-review-*.csv.gz"))
    lines = [
        "% Auto-generated by paper/scripts/generate_supplement.py",
        r"\begin{longtable}{@{}L{0.66\linewidth}r@{}}",
        r"\caption{Generated report artifact inventory.}\label{tab:supp-artifacts}\\",
        r"\toprule",
        r"Artifact & Size (KB) \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Artifact & Size (KB) \\",
        r"\midrule",
        r"\endhead",
    ]
    for path in paths:
        size_kb = path.stat().st_size / 1024
        lines.append(f"{latex_escape(str(path.relative_to(ROOT)))} & {size_kb:.1f} \\\\")
    lines.extend([r"\bottomrule", r"\end{longtable}", ""])
    write("supplement_artifacts.tex", "\n".join(lines))


def source_status(row: dict[str, str]) -> str:
    has_n = bool(row["n"] and row["n"] != "0")
    if row["sourceUrl"]:
        return "URL+n" if has_n else "URL"
    if has_n:
        return "counted"
    return "synthesis"


def calibration_source_matrix() -> None:
    rows = read_rows(CALIBRATION_SOURCE)
    lines = [
        "% Auto-generated by paper/scripts/generate_supplement.py",
        r"{\scriptsize",
        r"\setlength{\tabcolsep}{2pt}",
        r"\begin{longtable}{@{}L{0.15\linewidth}L{0.23\linewidth}L{0.19\linewidth}rL{0.07\linewidth}L{0.09\linewidth}L{0.12\linewidth}@{}}",
        r"\caption{Calibration source-observation matrix.}\label{tab:supp-calibration-sources}\\",
        r"\toprule",
        r"Profile & Target & Method & $n$ & Rel. & Val. & Source status \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Profile & Target & Method & $n$ & Rel. & Val. & Source status \\",
        r"\midrule",
        r"\endhead",
    ]
    for row in rows:
        n = row["n"] if row["n"] and row["n"] != "0" else "--"
        lines.append(
            " & ".join(
                [
                    latex_escape(row["profileKey"]),
                    latex_escape(row["label"]),
                    latex_escape(row["method"]),
                    latex_escape(n),
                    latex_escape(row["reliability"]),
                    "yes" if row["useForValidation"].lower() == "true" else "no",
                    latex_escape(source_status(row)),
                ]
            )
            + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\noindent\footnotesize Rows marked Val.=yes are the only rows counted in the validation-style diagnostics. Rows marked synthesis, contextual public-trust proxy, or normalized cost benchmark remain visible as stress-test assumptions but are not treated as source-backed validation evidence. The CSV source retains full notes, source names, URLs when available, and construction notes for every target.",
            r"}",
            "",
        ]
    )
    write("supplement_calibration_sources.tex", "\n".join(lines))


def model_weight_summary() -> None:
    lines = [
        "% Auto-generated by paper/scripts/generate_supplement.py",
        r"{\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{longtable}{@{}L{0.20\linewidth}L{0.69\linewidth}@{}}",
        r"\caption{Core model equations and fixed weights.}\label{tab:supp-model-weights}\\",
        r"\toprule",
        r"Component & Fixed construction used in the reported campaigns \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Component & Fixed construction used in the reported campaigns \\",
        r"\midrule",
        r"\endhead",
        r"Shadow-docket abuse & Emergency cases start from procedure risk: fast shadow docket 0.72, reasoned emergency panel 0.34, full-court emergency 0.20, merits-follow-up design 0.16. The score adds no-merits penalty 0.26, relief-without-merits penalty 0.18, impact from salient relief or high rights threat, executive pressure 0.12, and subtracts emergency reason-giving 0.22. \\",
        r"Legal stability & $1 - 0.32$ reversal magnitude $- 0.28$ constitutional conflict $- 0.22$ shadow abuse $- 0.08$ dissent intensity $- 0.06$ concurrence fragmentation $+ 0.12$ scenario stability preference, truncated to $[0,1]$. \\",
        r"Legitimacy & Weighted average of case public trust 0.24, dynamic public trust 0.12, transparency 0.18, majority share 0.12, rights protection 0.18, inverse partisan alignment 0.14, inverse shadow abuse 0.14, and constitutional conflict penalty 0.18. \\",
        r"Rights protection & Merits invalidation begins at 0.44 plus rights-threat weight 0.54 and legal-ambiguity penalty 0.08. Emergency relief without merits begins at 0.38 plus rights-threat weight 0.40 and time-to-review penalty 0.08. No-relief outcomes fall with rights threat and delay. Overrides reduce protection when rights threat is high. \\",
        r"Constitutional conflict & Adds countermajoritarian clash from merits invalidation or emergency relief, override penalty 0.36, shadow-abuse weight 0.30, cross-check conflict 0.24, executive pressure 0.10, lower-court panel skew 0.05, state-federal tension 0.12, and intercourt conflict 0.10. \\",
        r"Compliance and enforcement & Compliance starts at 0.46 and moves with legitimacy 0.24, dynamic compliance norm 0.22, court independence 0.06, conflict penalties, emergency-without-merits penalty 0.08, override penalty 0.10, and executive pressure 0.08. Executive implementation, agency nonacquiescence, reenactment, and local compliance are separate downstream Bernoulli draws. \\",
        r"Institutional cost & Total cost is $0.25$ direct court cost $+ 0.20$ upstream screening $+ 0.20$ capacity strain $+ 0.18$ delay $+ 0.17$ implementation complexity. The subcomponents depend on court size, review structure, docket control, emergency procedure, council screening, cross-checking, and panel/en banc design. \\",
        r"Directional score & Unweighted average of 23 display metrics after reversing lower-is-better measures. It is a diagnostic display score and not a welfare function or fitted objective. \\",
        r"\bottomrule",
        r"\end{longtable}",
        r"}",
        "",
    ]
    write("supplement_model_weights.tex", "\n".join(lines))


def main() -> None:
    model_weight_summary()
    scenario_matrix()
    sensitivity_matrix()
    calibration_source_matrix()
    artifact_inventory()


if __name__ == "__main__":
    main()
