#!/usr/bin/env python3
"""Generate compact LaTeX tables for the supplementary appendix."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPORT_DIR = ROOT / "reports"
TABLE_DIR = ROOT / "paper" / "tables"
CALIBRATION_SOURCE = ROOT / "config" / "calibration-source-observations.csv"
RESEARCH_DIR = ROOT / "config" / "research"
CONTEXT_DIR = ROOT / "config" / "context"


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def latex_escape(value: str) -> str:
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    return "".join(replacements.get(char, char) for char in value)


def latex_code_list(value: str) -> str:
    escaped = latex_escape(value).replace("; ", r";\newline ")
    breaks = {
        "ConstitutionalReviewProcess": r"Constitutional\hspace{0pt}Review\hspace{0pt}Process",
        "DecisionMechanismModel": r"Decision\hspace{0pt}Mechanism\hspace{0pt}Model",
        "PostDecisionResponseModel": r"Post\hspace{0pt}Decision\hspace{0pt}Response\hspace{0pt}Model",
        "EmergencyDocketModel": r"Emergency\hspace{0pt}Docket\hspace{0pt}Model",
        "InstitutionalCostModel": r"Institutional\hspace{0pt}Cost\hspace{0pt}Model",
        "CampaignCalibrationEvaluator": r"Campaign\hspace{0pt}Calibration\hspace{0pt}Evaluator",
        "DirectionalScoreModel": r"Directional\hspace{0pt}Score\hspace{0pt}Model",
        "OutcomeScoreModel": r"Outcome\hspace{0pt}Score\hspace{0pt}Model",
    }
    for raw, replacement in breaks.items():
        escaped = escaped.replace(raw, replacement)
    return escaped


def num(value: str | float) -> str:
    return f"{float(value):.3f}"


MECHANISM_LABELS = {
    "strong_form_court": "Strong form",
    "weak_form_review": "Weak form",
    "suspended_declaration": "Suspended",
    "legislative_override_clause": "Override",
    "pre_enactment_review": "Pre-enact.",
    "abstract_review": "Abstract",
    "ombudsman_triggered_review": "Ombudsman",
    "constitutional_public_defender": "Defender",
    "rights_impact_statement": "Rights stmt.",
    "mandatory_legislative_response": "Response",
    "supranational_review": "Supranat.",
}


def mechanism_label(value: str) -> str:
    return MECHANISM_LABELS.get(value, value.replace("_", " "))


def write(name: str, content: str) -> None:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    (TABLE_DIR / name).write_text(content, encoding="utf-8")


def scenario_matrix() -> None:
    rows = read_rows(REPORT_DIR / "constitutional-review-campaign-v0.csv")
    lines = [
        "% Auto-generated by paper/scripts/generate_supplement.py",
        r"{\scriptsize",
        r"\setlength{\tabcolsep}{2pt}",
        r"\begin{longtable}{@{}L{0.12\linewidth}L{0.23\linewidth}L{0.11\linewidth}rrrrrr@{}}",
        r"\caption{Full main-campaign scenario matrix.}\label{tab:supp-scenario-matrix}\\",
        r"\toprule",
        r"Case & Scenario & Mechanism & Score & Dem. const. & Rights & Veto $\downarrow$ & Culture $\downarrow$ & Cost $\downarrow$ \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Case & Scenario & Mechanism & Score & Dem. const. & Rights & Veto $\downarrow$ & Culture $\downarrow$ & Cost $\downarrow$ \\",
        r"\midrule",
        r"\endhead",
    ]
    for row in rows:
        lines.append(
            " & ".join(
                [
                    latex_escape(row["caseName"]),
                    latex_escape(row["scenario"]),
                    latex_escape(mechanism_label(row["reviewMechanism"])),
                    num(row["directionalScore"]),
                    num(row["democraticConstitutionalism"]),
                    num(row["rightsProtection"]),
                    num(row["vetoRelocationRisk"]),
                    num(row["politicalCultureSensitivity"]),
                    num(row["totalInstitutionalCost"]),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{longtable}", r"}", ""])
    write("supplement_scenario_matrix.tex", "\n".join(lines))


def sensitivity_matrix() -> None:
    rows = read_rows(REPORT_DIR / "constitutional-review-sensitivity-v1.csv")
    lines = [
        "% Auto-generated by paper/scripts/generate_supplement.py",
        r"{\scriptsize",
        r"\setlength{\tabcolsep}{2pt}",
        r"\begin{longtable}{@{}L{0.19\linewidth}L{0.22\linewidth}rrrrrr@{}}",
        r"\caption{Sensitivity-campaign diagnostic matrix.}\label{tab:supp-sensitivity}\\",
        r"\toprule",
        r"Stress case & Scenario & Score & Dem. const. & Veto $\downarrow$ & Transplant & Culture $\downarrow$ & Trust \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Stress case & Scenario & Score & Dem. const. & Veto $\downarrow$ & Transplant & Culture $\downarrow$ & Trust \\",
        r"\midrule",
        r"\endhead",
    ]
    for row in rows:
        lines.append(
            " & ".join(
                [
                    latex_escape(row["caseName"]),
                    latex_escape(row["scenario"]),
                    num(row["directionalScore"]),
                    num(row["democraticConstitutionalism"]),
                    num(row["vetoRelocationRisk"]),
                    num(row["legalTransplantFeasibility"]),
                    num(row["politicalCultureSensitivity"]),
                    num(row["publicTrust"]),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{longtable}", r"}", ""])
    write("supplement_sensitivity_matrix.tex", "\n".join(lines))


def artifact_inventory() -> None:
    paths = sorted(REPORT_DIR.glob("constitutional-review-*.csv"))
    lines = [
        "% Auto-generated by paper/scripts/generate_supplement.py",
        r"\begin{longtable}{@{}L{0.66\linewidth}r@{}}",
        r"\caption{Generated report artifact inventory.}\label{tab:supp-artifacts}\\",
        r"\toprule",
        r"Artifact & Size (KB) \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Artifact & Size (KB) \\",
        r"\midrule",
        r"\endhead",
    ]
    for path in paths:
        size_kb = path.stat().st_size / 1024
        lines.append(f"{latex_escape(str(path.relative_to(ROOT)))} & {size_kb:.1f} \\\\")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\noindent\footnotesize Compressed case-level \texttt{*.csv.gz} exports are generated by the campaign commands, excluded from the anonymous review bundle, and omitted from this tracked size table because their local file sizes depend on the last full campaign run.",
            "",
        ]
    )
    write("supplement_artifacts.tex", "\n".join(lines))


def source_status(row: dict[str, str]) -> str:
    has_n = bool(row["n"] and row["n"] != "0")
    if row["sourceUrl"]:
        return "URL+n" if has_n else "URL"
    if has_n:
        return "counted"
    return "synthesis"


def calibration_source_matrix() -> None:
    rows = read_rows(CALIBRATION_SOURCE)
    lines = [
        "% Auto-generated by paper/scripts/generate_supplement.py",
        r"{\scriptsize",
        r"\setlength{\tabcolsep}{2pt}",
        r"\begin{longtable}{@{}L{0.15\linewidth}L{0.23\linewidth}L{0.19\linewidth}rL{0.07\linewidth}L{0.09\linewidth}L{0.12\linewidth}@{}}",
        r"\caption{Calibration source-observation matrix.}\label{tab:supp-calibration-sources}\\",
        r"\toprule",
        r"Profile & Target & Method & $n$ & Rel. & Val. & Source status \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Profile & Target & Method & $n$ & Rel. & Val. & Source status \\",
        r"\midrule",
        r"\endhead",
    ]
    for row in rows:
        n = row["n"] if row["n"] and row["n"] != "0" else "--"
        lines.append(
            " & ".join(
                [
                    latex_escape(row["profileKey"]),
                    latex_escape(row["label"]),
                    latex_escape(row["method"]),
                    latex_escape(n),
                    latex_escape(row["reliability"]),
                    "yes" if row["useForValidation"].lower() == "true" else "no",
                    latex_escape(source_status(row)),
                ]
            )
            + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\noindent\footnotesize Rows marked Val.=yes are the only rows counted in the external diagnostic comparisons. Rows marked synthesis, contextual public-trust proxy, or normalized cost benchmark remain visible as stress-test assumptions but are not treated as source-backed validation evidence. The source-observation data retain full notes, source names, URLs when available, and construction notes for every target.",
            r"}",
            "",
        ]
    )
    write("supplement_calibration_sources.tex", "\n".join(lines))


def research_roadmap_matrix() -> None:
    files = [
        (RESEARCH_DIR / "empirical-target-roadmap.csv", "Court calibration packs"),
        (RESEARCH_DIR / "legislative-response-evidence.csv", "Legislative response"),
        (RESEARCH_DIR / "legislative-response-source-candidates.csv", "Response source candidates"),
        (RESEARCH_DIR / "comparative-calibration-source-candidates.csv", "Comparative target candidates"),
        (RESEARCH_DIR / "transplant-feasibility-factors.csv", "Transplant factors"),
        (RESEARCH_DIR / "transplant-indicator-operationalization.csv", "Transplant indicator mapping"),
        (RESEARCH_DIR / "compliance-enforcement-targets.csv", "Compliance channels"),
        (RESEARCH_DIR / "case-selection-targets.csv", "Case selection"),
        (CONTEXT_DIR / "country-year-context.csv", "Diagnostic political-culture and implementation contexts"),
    ]
    lines = [
        "% Auto-generated by paper/scripts/generate_supplement.py",
        r"{\scriptsize",
        r"\setlength{\tabcolsep}{2pt}",
        r"\begin{longtable}{@{}L{0.36\linewidth}rL{0.39\linewidth}@{}}",
        r"\caption{Empirical data-development files.}\label{tab:supp-research-roadmap}\\",
        r"\toprule",
        r"Data file & Rows & Purpose \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Data file & Rows & Purpose \\",
        r"\midrule",
        r"\endhead",
    ]
    for path, purpose in files:
        rows = read_rows(path)
        lines.append(
            " & ".join(
                [
                    latex_escape(str(path.relative_to(ROOT))),
                    str(len(rows)),
                    latex_escape(purpose),
                ]
            )
            + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\noindent\footnotesize Data-development and candidate rows are source-gathering tasks, not calibration targets. A candidate row should move into the calibration source matrix only after URLs, denominators, period coverage, coding rules, and a direct simulator analogue are documented. Candidate files preserve provisional denominators while preventing unverified secondary research summaries from being counted as validation evidence.",
            r"}",
            "",
        ]
    )
    write("supplement_research_roadmap.tex", "\n".join(lines))


def model_weight_summary() -> None:
    lines = [
        "% Auto-generated by paper/scripts/generate_supplement.py",
        r"{\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{longtable}{@{}L{0.20\linewidth}L{0.69\linewidth}@{}}",
        r"\caption{Core model equations and fixed weights.}\label{tab:supp-model-weights}\\",
        r"\toprule",
        r"Component & Fixed construction used in the reported campaigns \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Component & Fixed construction used in the reported campaigns \\",
        r"\midrule",
        r"\endhead",
        r"Emergency-process irregularity & Emergency cases start from procedure risk: fast shadow docket 0.72, reasoned emergency panel 0.34, full-court emergency 0.20, merits-follow-up design 0.16. The score adds no-merits penalty 0.26, relief-without-merits penalty 0.18, impact from salient relief or high rights threat, executive pressure 0.12, and subtracts emergency reason-giving 0.22. The report column remains \texttt{shadowDocketAbuse} for compatibility. \\",
        r"Legal stability & $1 - 0.32$ reversal magnitude $- 0.28$ constitutional-conflict index $- 0.22$ emergency irregularity $- 0.08$ dissent intensity $- 0.06$ concurrence fragmentation $+ 0.12$ scenario stability preference, truncated to $[0,1]$. \\",
        r"Modeled public-legitimacy proxy & Weighted average of case public trust 0.24, dynamic public trust 0.12, transparency 0.18, majority share 0.12, rights protection 0.18, inverse partisan alignment 0.14, inverse emergency irregularity 0.14, and constitutional-conflict penalty 0.18. \\",
        r"Rights protection & Merits invalidation begins at 0.44 plus rights-threat weight 0.54 and legal-ambiguity penalty 0.08. Emergency relief without merits begins at 0.38 plus rights-threat weight 0.40 and time-to-review penalty 0.08. No-relief outcomes fall with rights threat and delay. Overrides reduce protection when rights threat is high. \\",
        r"Constitutional-conflict index & Adds countermajoritarian clash from merits invalidation or emergency relief, override penalty 0.36, emergency-irregularity weight 0.30, cross-check conflict 0.24, executive pressure 0.10, lower-court panel skew 0.05, state-federal tension 0.12, and intercourt conflict 0.10. \\",
        r"Compliance and enforcement & Compliance starts at 0.46 and moves with legitimacy 0.24, dynamic compliance norm 0.22, implementation capacity 0.10, court independence 0.06, conflict penalties, emergency-without-merits penalty 0.08, override penalty 0.10, and executive pressure 0.08. Executive implementation, agency nonacquiescence, reenactment, and local compliance are separate downstream Bernoulli draws. \\",
        r"Institutional cost & Total cost is $0.25$ direct court cost $+ 0.20$ upstream screening $+ 0.20$ capacity strain $+ 0.18$ delay $+ 0.17$ implementation complexity. The subcomponents depend on court size, review structure, docket control, emergency procedure, council screening, cross-checking, and panel/en banc design. \\",
        r"Case selection access & Intake access combines structural review access, realized intake acceptance, litigant capacity, public-interest support, ombudsman or public-defender participation, rights-impact statements, and inverse government repeat-player advantage. \\",
        r"Legislative-response credibility & Response credibility combines mechanism triggers, rights threat, public support, legislative mandate, party-system compatibility, civil-society capacity, implementation capacity, and inverse electoral time pressure. \\",
        r"Directional score & Unweighted average of 35 display metrics after reversing lower-is-better measures. It is a diagnostic display score and not a welfare function or fitted objective. \\",
        r"Legal-transplant feasibility & Scenario transplant score, political-culture fit, case public trust, legal-tradition compatibility, implementation capacity, civil-society capacity, inverse institutional demand, and inverse political mismatch. Institutional demand combines total cost, upstream screening, complexity, intake screening, and a synthetic-mechanism penalty. \\",
        r"Political-culture sensitivity & Mechanism fragility baseline plus low culture fit, legislative conflict, partisan pressure, party fragmentation, electoral time pressure, constitutional-conflict index, implementation complexity, state-federal tension, and low implementation or civil-society capacity. Lower is better. \\",
        r"Veto-relocation risk & Low-rights interventions, council or cross-check veto points, intake-screening intensity, upstream cost, low acceptance rate, high independence, low transparency, government repeat-player advantage, and low case-selection access increase risk. Legislative response and rights-threat justification reduce it. \\",
        r"CJEU route mix & CJEU-style designs record preliminary-reference, appeal, and direct-action route flags as diagnostics. The route draw is bounded around the official 2024 incoming-case mix and is reported separately from the directional score. \\",
        r"Democratic constitutionalism & Legal stability 0.11, rights protection 0.18, legitimacy 0.12, democratic responsiveness 0.15, compliance 0.09, inverse conflict 0.08, inverse veto relocation 0.07, transplant feasibility 0.05, inverse culture sensitivity 0.03, response credibility 0.03, case-selection access 0.03, inverse government repeat-player advantage 0.03, and implementation capacity 0.03. \\",
        r"\end{longtable}",
        r"}",
        "",
    ]
    write("supplement_model_weights.tex", "\n".join(lines))


def model_crosswalk() -> None:
    rows = [
        (
            "Scenario catalog",
            "ScenarioCatalog; Scenario",
            "scenario key, design configuration, world spec",
            "review process factory and scenario metadata",
            "institutional mapping",
        ),
        (
            "Docket generation",
            "WorldGenerator; CaseFile",
            "world variables, imported legislative signals, random seed",
            "case-level facts, doctrine, policy domain, lower-court path",
            "synthetic input generator",
        ),
        (
            "Admission and access",
            "IntakeModel; IntakeEstimate",
            "case salience, rights threat, litigant capacity, public-interest support, repeat-player advantage, docket control",
            "reviewed flag, intake filings, screened filings, intake acceptance, case-selection access",
            "diagnostic plus source-range proxy rows",
        ),
        (
            "Emergency docket",
            "EmergencyDocketModel",
            "urgency, executive pressure, vote share, emergency procedure",
            "relief, reasons, vote disclosure, public disagreement, merits follow-up, emergency-process irregularity",
            "synthetic mechanism with source diagnostics",
        ),
        (
            "Merits voting",
            "ConstitutionalReviewProcess; VoteResult",
            "justice traits, policy position, rights threat, mandate, lower-court signals, thresholds",
            "strike vote share, invalidation, concurrence fragmentation, dissent intensity",
            "stylized decision model",
        ),
        (
            "Noncourt mechanisms",
            "DecisionMechanismModel; PostDecisionResponseModel",
            "review timing, ombudsman, public defender, rights statement, declaration, override, party context",
            "legislative response, response delay, response credibility, supranational route flags",
            "synthetic mechanism with source diagnostics",
        ),
        (
            "Compliance and enforcement",
            "ComplianceModel; ReactionState",
            "legitimacy proxy, constitutional-conflict index, implementation capacity, dynamic reaction state",
            "compliance, defiance, workaround, repeated litigation, executive implementation, nonacquiescence, reenactment, local compliance",
            "synthetic mechanism",
        ),
        (
            "Institutional cost",
            "InstitutionalCostModel; CostEstimate",
            "court size, structure, screening, emergency procedure, recusal, intake pressure",
            "direct court cost, upstream screening, capacity strain, delay, complexity, total cost",
            "normalized diagnostic",
        ),
        (
            "Outcome scoring",
            "OutcomeScoreModel; DirectionalScoreModel",
            "case outcomes, costs, access, response credibility, transplant and culture modifiers",
            "rights protection, conflict, democratic constitutionalism, veto relocation, directional display score",
            "synthetic diagnostic",
        ),
        (
            "Campaign and calibration",
            "CampaignRunner; CampaignCalibrationEvaluator",
            "scenario rows, case outcomes, calibration source-observation matrix",
            "CSV reports, uncertainty bands, external diagnostic comparisons, provenance manifests",
            "reporting and source-range diagnostics",
        ),
    ]
    lines = [
        "% Auto-generated by paper/scripts/generate_supplement.py",
        r"{\scriptsize",
        r"\setlength{\tabcolsep}{2pt}",
        r"\begin{longtable}{@{}L{0.15\linewidth}L{0.19\linewidth}L{0.23\linewidth}L{0.23\linewidth}L{0.10\linewidth}@{}}",
        r"\caption{Model-to-code crosswalk.}\label{tab:supp-model-crosswalk}\\",
        r"\toprule",
        r"Stage & Main module & Inputs & Outputs & Evidence status \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Stage & Main module & Inputs & Outputs & Evidence status \\",
        r"\midrule",
        r"\endhead",
    ]
    for stage, module, inputs, outputs, status in rows:
        lines.append(
            " & ".join(
                [
                    latex_escape(stage),
                    latex_code_list(module),
                    latex_escape(inputs),
                    latex_escape(outputs),
                    latex_escape(status),
                ]
            )
            + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\noindent\footnotesize The crosswalk identifies where each prose model component is implemented. Evidence status separates institutional mappings and source-range diagnostics from synthetic mechanisms and normalized display scores.",
            r"}",
            "",
        ]
    )
    write("supplement_model_crosswalk.tex", "\n".join(lines))


def main() -> None:
    model_weight_summary()
    model_crosswalk()
    scenario_matrix()
    sensitivity_matrix()
    calibration_source_matrix()
    research_roadmap_matrix()
    artifact_inventory()


if __name__ == "__main__":
    main()
