package courtsim.institution;


public enum ReviewMechanism
{
	STRONG_FORM_COURT,
	WEAK_FORM_REVIEW,
	SUSPENDED_DECLARATION,
	LEGISLATIVE_OVERRIDE_CLAUSE,
	PRE_ENACTMENT_REVIEW,
	ABSTRACT_REVIEW,
	OMBUDSMAN_TRIGGERED_REVIEW,
	CONSTITUTIONAL_PUBLIC_DEFENDER,
	RIGHTS_IMPACT_STATEMENT,
	MANDATORY_LEGISLATIVE_RESPONSE,
	SUPRANATIONAL_REVIEW
}
