package courtsim.institution;

public enum ReviewArchetype {
    DISCRETIONARY_APPELLATE_LEAVE,
    CONSTITUTIONAL_COMPLAINT,
    PRE_ENACTMENT_COUNCIL,
    MIXED_ABSTRACT_CONCRETE,
    DECLARATION_ONLY_PARLIAMENTARY,
    SUPRANATIONAL_TREATY
}
