package courtsim.simulation;

import courtsim.util.Values;

import java.util.List;

public record ScenarioReport(
        String scenarioKey,
        String scenarioName,
        int totalCases,
        int reviewedCases,
        int invalidations,
        int emergencyOrders,
        int emergencyReliefs,
        int meritsReviews,
        int meritsInvalidations,
        int overrides,
        double reviewRate,
        double emergencyReliefRate,
        double meritsReviewRate,
        double meritsInvalidationRate,
        double legalStability,
        double rightsProtection,
        double partisanAlignment,
        double shadowDocketAbuse,
        double legitimacy,
        double reversalRate,
        double constitutionalConflict,
        double democraticResponsiveness,
        double independenceAccountabilityBalance,
        double concurrenceFragmentation,
        double dissentIntensity,
        double recusalRate,
        double enBancRate,
        double crossCheckRate,
        double councilScreenRate,
        double overrideRate,
        double lowerCourtConflict,
        double averageTimeToReview,
        double replacementRate,
        double stateCaseShare,
        double mixedJurisdictionShare,
        double averageLowerCourtDepth,
        double stateFederalTension,
        double intercourtConflict,
        double complianceRate,
        double defianceRate,
        double workaroundRate,
        double repeatedLitigationRate,
        double executiveImplementationRate,
        double agencyNonacquiescenceRate,
        double legislativeReenactmentRate,
        double localGovernmentComplianceRate,
        double publicTrust,
        double legislativeConflict,
        double courtCurbingPressure,
        double amendmentPressure,
        double institutionalBudgetCost,
        double institutionalDelayCost,
        double implementationComplexity,
        double totalInstitutionalCost,
        List<SegmentReport> periodReports,
        List<SegmentReport> doctrineReports,
        List<SegmentReport> pipelineReports,
        List<SegmentReport> policyDomainReports,
        List<CompositionReport> compositionReports,
        double administrativeLoad
) {
    public double directionalScore() {
        return Values.average(
                legalStability,
                rightsProtection,
                Values.lowerIsBetter(partisanAlignment),
                Values.lowerIsBetter(shadowDocketAbuse),
                legitimacy,
                Values.lowerIsBetter(reversalRate),
                Values.lowerIsBetter(emergencyReliefRate),
                Values.lowerIsBetter(meritsInvalidationRate),
                Values.lowerIsBetter(constitutionalConflict),
                democraticResponsiveness,
                independenceAccountabilityBalance,
                complianceRate,
                Values.lowerIsBetter(defianceRate),
                Values.lowerIsBetter(workaroundRate),
                executiveImplementationRate,
                Values.lowerIsBetter(agencyNonacquiescenceRate),
                Values.lowerIsBetter(legislativeReenactmentRate),
                localGovernmentComplianceRate,
                Values.lowerIsBetter(administrativeLoad),
                Values.lowerIsBetter(totalInstitutionalCost)
        );
    }
}
