#!/usr/bin/env python3
"""Assemble anonymous JLC review and replication bundles."""

from __future__ import annotations

import shutil
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SUBMISSION_DIR = ROOT / "submission"
MANUSCRIPT_PDF = ROOT / "paper" / "build" / "main.pdf"
SUPPLEMENT_PDF = ROOT / "paper" / "build" / "supplementary-appendix.pdf"


REPLICATION_PREFIXES = [
    "AGENTS.md",
    "Makefile",
    "README.md",
    "config",
    "data",
    "docs",
    "paper",
    "reports",
    "scripts",
    "src",
]

EXCLUDED_SUFFIXES = {
    ".aux",
    ".log",
    ".out",
    ".synctex.gz",
}

EXCLUDED_PARTS = {
    ".git",
    ".idea",
    "out",
    "submission",
    "__pycache__",
}


def ensure_inputs() -> None:
    missing = [path for path in [MANUSCRIPT_PDF, SUPPLEMENT_PDF] if not path.exists()]
    if missing:
        joined = ", ".join(str(path.relative_to(ROOT)) for path in missing)
        raise SystemExit(f"missing build artifact(s): {joined}; run make paper supplement first")


def should_include(path: Path) -> bool:
    relative = path.relative_to(ROOT)
    if any(part in EXCLUDED_PARTS for part in relative.parts):
        return False
    if any(str(relative).startswith(prefix) for prefix in REPLICATION_PREFIXES):
        return not any(str(relative).endswith(suffix) for suffix in EXCLUDED_SUFFIXES)
    return False


def write_zip(path: Path, files: list[Path]) -> None:
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for file_path in files:
            archive.write(file_path, file_path.relative_to(ROOT))


def replication_files() -> list[Path]:
    return sorted(path for path in ROOT.rglob("*") if path.is_file() and should_include(path))


def write_readme() -> Path:
    readme = SUBMISSION_DIR / "README.md"
    readme.write_text(
        """# Journal of Law and Courts Review Bundle

This directory was generated by `make submission-bundle`.

Files:

- `anonymous-manuscript.pdf`: main manuscript for anonymous review.
- `supplementary-appendix.pdf`: compact technical appendix for review.
- `source-files.zip`: editable LaTeX source for the manuscript and appendix.
- `replication-package.zip`: Java source, configuration, calibration source observations, generated reports, compressed case-level outputs, provenance manifests, and reproduction commands.
- `jlc-review-bundle.zip`: single upload bundle containing the PDFs and the two ZIP archives.

The archive is intended for anonymous review. Repository metadata, IDE files, build directories, and local machine paths are excluded.
""",
        encoding="utf-8",
    )
    return readme


def main() -> None:
    ensure_inputs()
    if SUBMISSION_DIR.exists():
        shutil.rmtree(SUBMISSION_DIR)
    SUBMISSION_DIR.mkdir(parents=True)

    manuscript_target = SUBMISSION_DIR / "anonymous-manuscript.pdf"
    supplement_target = SUBMISSION_DIR / "supplementary-appendix.pdf"
    shutil.copy2(MANUSCRIPT_PDF, manuscript_target)
    shutil.copy2(SUPPLEMENT_PDF, supplement_target)

    source_files = [
        ROOT / "paper" / "main.tex",
        ROOT / "paper" / "supplementary-appendix.tex",
        ROOT / "paper" / "cup-journal.cls",
        *sorted((ROOT / "paper" / "figures").glob("*.tex")),
        *sorted((ROOT / "paper" / "tables").glob("*.tex")),
        *sorted((ROOT / "paper" / "scripts").glob("*.py")),
        ROOT / "paper" / "references.bib",
        ROOT / "paper" / "accessibility-descriptions.md",
    ]
    source_zip = SUBMISSION_DIR / "source-files.zip"
    write_zip(source_zip, [path for path in source_files if path.exists()])

    replication_zip = SUBMISSION_DIR / "replication-package.zip"
    write_zip(replication_zip, replication_files())

    readme = write_readme()
    bundle_zip = SUBMISSION_DIR / "jlc-review-bundle.zip"
    write_zip(bundle_zip, [manuscript_target, supplement_target, source_zip, replication_zip, readme])

    manifest = SUBMISSION_DIR / "manifest.txt"
    manifest.write_text(
        "\n".join(
            [
                "anonymous-manuscript.pdf",
                "supplementary-appendix.pdf",
                "source-files.zip",
                "replication-package.zip",
                "jlc-review-bundle.zip",
                "README.md",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Wrote {bundle_zip.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
